sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.1
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem update --system
  - gem install bundler
script:
  - bundle exec rspec
notifications:
  email: false