sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.1
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem update --system
  - gem install bundler
script:
  - bundle exec rspec
notifications:
  email: false
addons:
  code_climate:
    repo_token: c10c2e0f19f128e1104891ce01b180b0f226ee1c58ba42a1bda3cfa0c7a2784d
after_success:
  - bundle exec codeclimate-test-reporter